/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpAriExp extends PExp
{
    private PExpVirgula _expVirgula_;
    private PExpressaoAritmetica _expressaoAritmetica_;

    public AExpAriExp()
    {
        // Constructor
    }

    public AExpAriExp(
        @SuppressWarnings("hiding") PExpVirgula _expVirgula_,
        @SuppressWarnings("hiding") PExpressaoAritmetica _expressaoAritmetica_)
    {
        // Constructor
        setExpVirgula(_expVirgula_);

        setExpressaoAritmetica(_expressaoAritmetica_);

    }

    @Override
    public Object clone()
    {
        return new AExpAriExp(
            cloneNode(this._expVirgula_),
            cloneNode(this._expressaoAritmetica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpAriExp(this);
    }

    public PExpVirgula getExpVirgula()
    {
        return this._expVirgula_;
    }

    public void setExpVirgula(PExpVirgula node)
    {
        if(this._expVirgula_ != null)
        {
            this._expVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expVirgula_ = node;
    }

    public PExpressaoAritmetica getExpressaoAritmetica()
    {
        return this._expressaoAritmetica_;
    }

    public void setExpressaoAritmetica(PExpressaoAritmetica node)
    {
        if(this._expressaoAritmetica_ != null)
        {
            this._expressaoAritmetica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoAritmetica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expVirgula_)
            + toString(this._expressaoAritmetica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expVirgula_ == child)
        {
            this._expVirgula_ = null;
            return;
        }

        if(this._expressaoAritmetica_ == child)
        {
            this._expressaoAritmetica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expVirgula_ == oldChild)
        {
            setExpVirgula((PExpVirgula) newChild);
            return;
        }

        if(this._expressaoAritmetica_ == oldChild)
        {
            setExpressaoAritmetica((PExpressaoAritmetica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
