/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AParaPassoComandos extends PComandos
{
    private PVariavel _variavel_;
    private TNumero _inicio_;
    private TNumero _passos_;
    private TNumero _fim_;
    private final LinkedList<PComandos> _comandos_ = new LinkedList<PComandos>();

    public AParaPassoComandos()
    {
        // Constructor
    }

    public AParaPassoComandos(
        @SuppressWarnings("hiding") PVariavel _variavel_,
        @SuppressWarnings("hiding") TNumero _inicio_,
        @SuppressWarnings("hiding") TNumero _passos_,
        @SuppressWarnings("hiding") TNumero _fim_,
        @SuppressWarnings("hiding") List<?> _comandos_)
    {
        // Constructor
        setVariavel(_variavel_);

        setInicio(_inicio_);

        setPassos(_passos_);

        setFim(_fim_);

        setComandos(_comandos_);

    }

    @Override
    public Object clone()
    {
        return new AParaPassoComandos(
            cloneNode(this._variavel_),
            cloneNode(this._inicio_),
            cloneNode(this._passos_),
            cloneNode(this._fim_),
            cloneList(this._comandos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaPassoComandos(this);
    }

    public PVariavel getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PVariavel node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    public TNumero getInicio()
    {
        return this._inicio_;
    }

    public void setInicio(TNumero node)
    {
        if(this._inicio_ != null)
        {
            this._inicio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicio_ = node;
    }

    public TNumero getPassos()
    {
        return this._passos_;
    }

    public void setPassos(TNumero node)
    {
        if(this._passos_ != null)
        {
            this._passos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._passos_ = node;
    }

    public TNumero getFim()
    {
        return this._fim_;
    }

    public void setFim(TNumero node)
    {
        if(this._fim_ != null)
        {
            this._fim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fim_ = node;
    }

    public LinkedList<PComandos> getComandos()
    {
        return this._comandos_;
    }

    public void setComandos(List<?> list)
    {
        for(PComandos e : this._comandos_)
        {
            e.parent(null);
        }
        this._comandos_.clear();

        for(Object obj_e : list)
        {
            PComandos e = (PComandos) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._comandos_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavel_)
            + toString(this._inicio_)
            + toString(this._passos_)
            + toString(this._fim_)
            + toString(this._comandos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        if(this._inicio_ == child)
        {
            this._inicio_ = null;
            return;
        }

        if(this._passos_ == child)
        {
            this._passos_ = null;
            return;
        }

        if(this._fim_ == child)
        {
            this._fim_ = null;
            return;
        }

        if(this._comandos_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variavel_ == oldChild)
        {
            setVariavel((PVariavel) newChild);
            return;
        }

        if(this._inicio_ == oldChild)
        {
            setInicio((TNumero) newChild);
            return;
        }

        if(this._passos_ == oldChild)
        {
            setPassos((TNumero) newChild);
            return;
        }

        if(this._fim_ == oldChild)
        {
            setFim((TNumero) newChild);
            return;
        }

        for(ListIterator<PComandos> i = this._comandos_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandos) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
