/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AInteiroValor extends PValor
{
    private TNumInt _numInt_;

    public AInteiroValor()
    {
        // Constructor
    }

    public AInteiroValor(
        @SuppressWarnings("hiding") TNumInt _numInt_)
    {
        // Constructor
        setNumInt(_numInt_);

    }

    @Override
    public Object clone()
    {
        return new AInteiroValor(
            cloneNode(this._numInt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInteiroValor(this);
    }

    public TNumInt getNumInt()
    {
        return this._numInt_;
    }

    public void setNumInt(TNumInt node)
    {
        if(this._numInt_ != null)
        {
            this._numInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numInt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numInt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numInt_ == child)
        {
            this._numInt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numInt_ == oldChild)
        {
            setNumInt((TNumInt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
