/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class TFimprograma extends Token
{
    public TFimprograma()
    {
        super.setText("fim.");
    }

    public TFimprograma(int line, int pos)
    {
        super.setText("fim.");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFimprograma(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFimprograma(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFimprograma text.");
    }
}
